# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build stable version
      run: gradle buildPlugin -PintellijPublishToken=unk -PbuildType=stable
    - name: Build eap version
      run: gradle buildPlugin -PintellijPublishToken=unk -PbuildType=eap
    - name: Rename eap
      run: mv build/distributions/*-EAP.zip build/distributions/ApplicationInsightsDebugLogViewer-EAP.zip
    - name: Rename stable
      run: mv build/distributions/*[0-9].zip build/distributions/ApplicationInsightsDebugLogViewer.zip
    - name: Upload eap artifact
      uses: actions/upload-artifact@v2-preview
      with:
        # Artifact name
        name: eap.zip
        # Directory containing files to upload
        path: build/distributions/ApplicationInsightsDebugLogViewer-EAP.zip
    - name: Upload stable artifact
      uses: actions/upload-artifact@v2-preview
      with:
        # Artifact name
        name: stable.zip
        # Directory containing files to upload
        path: build/distributions/ApplicationInsightsDebugLogViewer.zip
