# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build plugin
      uses: eskatos/gradle-command-action@v1.4.0
      with:
        arguments: buildPlugin --stacktrace
    - name: Unpack Distribution
      shell: pwsh
      run: scripts/Unpack-Distribution.ps1
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: SpecFlowPlugin
        path: build/distributions/unpacked