# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build stable version
      run: gradle buildPlugin -PintellijPublishToken=unk -PbuildType=stable
    - name: Build eap version
      run: gradle buildPlugin -PintellijPublishToken=unk -PbuildType=eap
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ApplicationInsightsDebugLogViewer
        # Directory containing files to upload
        path: build/distributions/
